- name: To install nginx and run it 
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Run the nginx
    ansible.builtin.service:
      name: nginx
      state: started
  - name: Copy file with owner and give permissions
    ansible.builtin.copy:
      src: index.html
      dest: /usr/share/nginx/html/
      owner: root
      group: root
      mode: '0644'
